## EDA

In [2]:
!python -m pip install --user -U ydata-profiling

Collecting ydata-profiling
  Downloading ydata_profiling-4.18.1-py2.py3-none-any.whl.metadata (22 kB)
Collecting scipy<1.17,>=1.8 (from ydata-profiling)
  Downloading scipy-1.16.3-cp311-cp311-win_amd64.whl.metadata (60 kB)
     ---------------------------------------- 0.0/60.8 kB ? eta -:--:--
     ------ --------------------------------- 10.2/60.8 kB ? eta -:--:--
     ---------------------------------------- 60.8/60.8 kB 1.1 MB/s eta 0:00:00
Requirement already satisfied: pandas!=1.4.0,<3.0,>1.5 in c:\python311\lib\site-packages (from ydata-profiling) (2.0.3)
Requirement already satisfied: matplotlib<=3.10,>=3.5 in c:\python311\lib\site-packages (from ydata-profiling) (3.7.1)
Collecting pydantic<3,>=2 (from ydata-profiling)
  Downloading pydantic-2.12.5-py3-none-any.whl.metadata (90 kB)
     ---------------------------------------- 0.0/90.6 kB ? eta -:--:--
     ---------------------------------------- 90.6/90.6 kB 5.0 MB/s eta 0:00:00
Collecting PyYAML<6.1,>=6.0.3 (from ydata-profiling)
  Downloading pyyaml-6.0.3-cp311-cp311-win_amd64.whl.metadata (2.4 kB)
Requirement already satisfied: jinja2<3.2,>=3.1.6 in c:\python311\lib\site-packages (from ydata-profiling) (3.1.6)
Collecting visions<0.8.2,>=0.7.5 (from visions[type_image_path]<0.8.2,>=0.7.5->ydata-profiling)
  Downloading visions-0.8.1-py3-none-any.whl.metadata (11 kB)
Requirement already satisfied: numpy<2.4,>=1.22 in c:\python311\lib\site-packages (from ydata-profiling) (2.3.5)
Collecting minify-html>=0.15.0 (from ydata-profiling)
  Downloading minify_html-0.18.1-cp311-cp311-win_amd64.whl.metadata (18 kB)
Collecting filetype>=1.0.0 (from ydata-profiling)
  Downloading filetype-1.2.0-py2.py3-none-any.whl.metadata (6.5 kB)
Collecting phik<0.13,>=0.12.5 (from ydata-profiling)
  Downloading phik-0.12.5-cp311-cp311-win_amd64.whl.metadata (5.6 kB)
Collecting requests<3,>=2.32.0 (from ydata-profiling)
  Using cached requests-2.32.5-py3-none-any.whl.metadata (4.9 kB)
Collecting tqdm<5,>=4.66.3 (from ydata-profiling)
  Downloading tqdm-4.67.3-py3-none-any.whl.metadata (57 kB)
     ---------------------------------------- 0.0/57.7 kB ? eta -:--:--
     ---------------------------------------- 57.7/57.7 kB ? eta 0:00:00
Requirement already satisfied: seaborn<0.14,>=0.10.1 in c:\python311\lib\site-packages (from ydata-profiling) (0.12.2)
Collecting multimethod<2,>=1.4 (from ydata-profiling)
  Downloading multimethod-1.12-py3-none-any.whl.metadata (9.6 kB)
Collecting statsmodels<1,>=0.13.2 (from ydata-profiling)
  Downloading statsmodels-0.14.6-cp311-cp311-win_amd64.whl.metadata (9.8 kB)
Collecting typeguard<5,>=4 (from ydata-profiling)
  Downloading typeguard-4.5.1-py3-none-any.whl.metadata (3.8 kB)
Collecting imagehash==4.3.2 (from ydata-profiling)
  Downloading ImageHash-4.3.2-py2.py3-none-any.whl.metadata (8.4 kB)
Collecting wordcloud>=1.9.4 (from ydata-profiling)
  Downloading wordcloud-1.9.6-cp311-cp311-win_amd64.whl.metadata (3.5 kB)
Collecting dacite<2,>=1.9 (from ydata-profiling)
  Downloading dacite-1.9.2-py3-none-any.whl.metadata (17 kB)
Collecting numba<0.63,>=0.60 (from ydata-profiling)
  Downloading numba-0.62.1-cp311-cp311-win_amd64.whl.metadata (2.9 kB)
Collecting PyWavelets (from imagehash==4.3.2->ydata-profiling)
  Downloading pywavelets-1.9.0-cp311-cp311-win_amd64.whl.metadata (7.6 kB)
Requirement already satisfied: pillow in c:\python311\lib\site-packages (from imagehash==4.3.2->ydata-profiling) (9.5.0)
Requirement already satisfied: MarkupSafe>=2.0 in c:\python311\lib\site-packages (from jinja2<3.2,>=3.1.6->ydata-profiling) (2.1.5)
Requirement already satisfied: contourpy>=1.0.1 in c:\users\hnico\appdata\roaming\python\python311\site-packages (from matplotlib<=3.10,>=3.5->ydata-profiling) (1.3.3)
Requirement already satisfied: cycler>=0.10 in c:\python311\lib\site-packages (from matplotlib<=3.10,>=3.5->ydata-profiling) (0.11.0)
Requirement already satisfied: fonttools>=4.22.0 in c:\python311\lib\site-packages (from matplotlib<=3.10,>=3.5->ydata-profiling) (4.39.2)
Requirement already satisfied: kiwisolver>=1.0.1 in c:\python311\lib\site-packages (from matplotlib<=3.10,>=3.5->ydata-profiling) (1.4.4)
Requirement already satisfied: packaging>=20.0 in c:\python311\lib\site-packages (from matplotlib<=3.10,>=3.5->ydata-profiling) (23.0)
Requirement already satisfied: pyparsing>=2.3.1 in c:\python311\lib\site-packages (from matplotlib<=3.10,>=3.5->ydata-profiling) (3.0.9)
Requirement already satisfied: python-dateutil>=2.7 in c:\python311\lib\site-packages (from matplotlib<=3.10,>=3.5->ydata-profiling) (2.8.2)
Collecting llvmlite<0.46,>=0.45.0dev0 (from numba<0.63,>=0.60->ydata-profiling)
  Downloading llvmlite-0.45.1-cp311-cp311-win_amd64.whl.metadata (5.0 kB)
Requirement already satisfied: pytz>=2020.1 in c:\python311\lib\site-packages (from pandas!=1.4.0,<3.0,>1.5->ydata-profiling) (2023.3)
Requirement already satisfied: tzdata>=2022.1 in c:\python311\lib\site-packages (from pandas!=1.4.0,<3.0,>1.5->ydata-profiling) (2023.3)
Requirement already satisfied: joblib>=0.14.1 in c:\python311\lib\site-packages (from phik<0.13,>=0.12.5->ydata-profiling) (1.4.0)
Collecting annotated-types>=0.6.0 (from pydantic<3,>=2->ydata-profiling)
  Downloading annotated_types-0.7.0-py3-none-any.whl.metadata (15 kB)
Collecting pydantic-core==2.41.5 (from pydantic<3,>=2->ydata-profiling)
  Downloading pydantic_core-2.41.5-cp311-cp311-win_amd64.whl.metadata (7.4 kB)
Collecting typing-extensions>=4.14.1 (from pydantic<3,>=2->ydata-profiling)
  Downloading typing_extensions-4.15.0-py3-none-any.whl.metadata (3.3 kB)
Collecting typing-inspection>=0.4.2 (from pydantic<3,>=2->ydata-profiling)
  Downloading typing_inspection-0.4.2-py3-none-any.whl.metadata (2.6 kB)
Requirement already satisfied: charset_normalizer<4,>=2 in c:\python311\lib\site-packages (from requests<3,>=2.32.0->ydata-profiling) (3.0.1)
Requirement already satisfied: idna<4,>=2.5 in c:\python311\lib\site-packages (from requests<3,>=2.32.0->ydata-profiling) (3.4)
Requirement already satisfied: urllib3<3,>=1.21.1 in c:\python311\lib\site-packages (from requests<3,>=2.32.0->ydata-profiling) (1.26.14)
Requirement already satisfied: certifi>=2017.4.17 in c:\python311\lib\site-packages (from requests<3,>=2.32.0->ydata-profiling) (2022.12.7)
Collecting patsy>=0.5.6 (from statsmodels<1,>=0.13.2->ydata-profiling)
  Downloading patsy-1.0.2-py2.py3-none-any.whl.metadata (3.6 kB)
Requirement already satisfied: colorama in c:\python311\lib\site-packages (from tqdm<5,>=4.66.3->ydata-profiling) (0.4.6)
Collecting attrs>=19.3.0 (from visions<0.8.2,>=0.7.5->visions[type_image_path]<0.8.2,>=0.7.5->ydata-profiling)
  Downloading attrs-25.4.0-py3-none-any.whl.metadata (10 kB)
Collecting networkx>=2.4 (from visions<0.8.2,>=0.7.5->visions[type_image_path]<0.8.2,>=0.7.5->ydata-profiling)
  Downloading networkx-3.6.1-py3-none-any.whl.metadata (6.8 kB)
Collecting puremagic (from visions<0.8.2,>=0.7.5->visions[type_image_path]<0.8.2,>=0.7.5->ydata-profiling)
  Downloading puremagic-1.30-py3-none-any.whl.metadata (5.8 kB)
Requirement already satisfied: six>=1.5 in c:\python311\lib\site-packages (from python-dateutil>=2.7->matplotlib<=3.10,>=3.5->ydata-profiling) (1.16.0)
Downloading ydata_profiling-4.18.1-py2.py3-none-any.whl (400 kB)
   ---------------------------------------- 0.0/400.4 kB ? eta -:--:--
   --------- ------------------------------ 92.2/400.4 kB 2.6 MB/s eta 0:00:01
   ---------------------------------------- 400.4/400.4 kB 6.2 MB/s eta 0:00:00
Downloading ImageHash-4.3.2-py2.py3-none-any.whl (296 kB)
   ---------------------------------------- 0.0/296.7 kB ? eta -:--:--
   ---------------------------------------- 296.7/296.7 kB 9.0 MB/s eta 0:00:00
Downloading dacite-1.9.2-py3-none-any.whl (16 kB)
Downloading filetype-1.2.0-py2.py3-none-any.whl (19 kB)
Downloading minify_html-0.18.1-cp311-cp311-win_amd64.whl (3.1 MB)
   ---------------------------------------- 0.0/3.1 MB ? eta -:--:--
   ----- ---------------------------------- 0.4/3.1 MB 8.7 MB/s eta 0:00:01
   ----------- ---------------------------- 0.9/3.1 MB 11.7 MB/s eta 0:00:01
   ----------------- ---------------------- 1.4/3.1 MB 11.0 MB/s eta 0:00:01
   ----------------------- ---------------- 1.8/3.1 MB 11.6 MB/s eta 0:00:01
   ------------------------------ --------- 2.4/3.1 MB 11.8 MB/s eta 0:00:01
   ---------------------------------------  3.1/3.1 MB 12.2 MB/s eta 0:00:01
   ---------------------------------------- 3.1/3.1 MB 11.7 MB/s eta 0:00:00
Downloading multimethod-1.12-py3-none-any.whl (10 kB)
Downloading numba-0.62.1-cp311-cp311-win_amd64.whl (2.7 MB)
   ---------------------------------------- 0.0/2.7 MB ? eta -:--:--
   ---------- ----------------------------- 0.7/2.7 MB 14.6 MB/s eta 0:00:01
   ------------------- -------------------- 1.4/2.7 MB 17.2 MB/s eta 0:00:01
   ---------------------------- ----------- 2.0/2.7 MB 15.6 MB/s eta 0:00:01
   ---------------------------------------  2.7/2.7 MB 17.2 MB/s eta 0:00:01
   ---------------------------------------- 2.7/2.7 MB 15.9 MB/s eta 0:00:00
Downloading phik-0.12.5-cp311-cp311-win_amd64.whl (675 kB)
   ---------------------------------------- 0.0/675.0 kB ? eta -:--:--
   --------------------------------------  665.6/675.0 kB 21.1 MB/s eta 0:00:01
   --------------------------------------- 675.0/675.0 kB 14.1 MB/s eta 0:00:00
Downloading pydantic-2.12.5-py3-none-any.whl (463 kB)
   ---------------------------------------- 0.0/463.6 kB ? eta -:--:--
   --------------------------------------- 463.6/463.6 kB 14.2 MB/s eta 0:00:00
Downloading pydantic_core-2.41.5-cp311-cp311-win_amd64.whl (2.0 MB)
   ---------------------------------------- 0.0/2.0 MB ? eta -:--:--
   ---------- ----------------------------- 0.5/2.0 MB 16.2 MB/s eta 0:00:01
   --------------- ------------------------ 0.8/2.0 MB 9.6 MB/s eta 0:00:01
   ----------------------------- ---------- 1.5/2.0 MB 13.3 MB/s eta 0:00:01
   ---------------------------------------  2.0/2.0 MB 14.3 MB/s eta 0:00:01
   ---------------------------------------- 2.0/2.0 MB 12.8 MB/s eta 0:00:00
Downloading pyyaml-6.0.3-cp311-cp311-win_amd64.whl (158 kB)
   ---------------------------------------- 0.0/158.8 kB ? eta -:--:--
   ---------------------------------------- 158.8/158.8 kB ? eta 0:00:00
Using cached requests-2.32.5-py3-none-any.whl (64 kB)
Downloading scipy-1.16.3-cp311-cp311-win_amd64.whl (38.7 MB)
   ---------------------------------------- 0.0/38.7 MB ? eta -:--:--
    --------------------------------------- 0.8/38.7 MB 23.7 MB/s eta 0:00:02
   - -------------------------------------- 1.6/38.7 MB 21.0 MB/s eta 0:00:02
   -- ------------------------------------- 2.5/38.7 MB 20.3 MB/s eta 0:00:02
   --- ------------------------------------ 3.1/38.7 MB 19.6 MB/s eta 0:00:02
   ---- ----------------------------------- 4.0/38.7 MB 21.4 MB/s eta 0:00:02
   ---- ----------------------------------- 4.6/38.7 MB 19.5 MB/s eta 0:00:02
   ----- ---------------------------------- 5.5/38.7 MB 20.6 MB/s eta 0:00:02
   ------ --------------------------------- 6.6/38.7 MB 21.0 MB/s eta 0:00:02
   ------- -------------------------------- 7.4/38.7 MB 20.6 MB/s eta 0:00:02
   -------- ------------------------------- 8.3/38.7 MB 21.3 MB/s eta 0:00:02
   --------- ------------------------------ 9.2/38.7 MB 21.1 MB/s eta 0:00:02
   ---------- ----------------------------- 9.8/38.7 MB 20.3 MB/s eta 0:00:02
   ----------- ---------------------------- 10.9/38.7 MB 21.1 MB/s eta 0:00:02
   ------------ --------------------------- 11.9/38.7 MB 21.1 MB/s eta 0:00:02
   ------------- -------------------------- 13.0/38.7 MB 21.8 MB/s eta 0:00:02
   -------------- ------------------------- 13.9/38.7 MB 22.6 MB/s eta 0:00:02
   --------------- ------------------------ 14.6/38.7 MB 22.6 MB/s eta 0:00:02
   ---------------- ----------------------- 15.7/38.7 MB 22.6 MB/s eta 0:00:02
   ----------------- ---------------------- 16.9/38.7 MB 23.4 MB/s eta 0:00:01
   ------------------ --------------------- 18.3/38.7 MB 25.2 MB/s eta 0:00:01
   -------------------- ------------------- 19.4/38.7 MB 25.2 MB/s eta 0:00:01
   --------------------- ------------------ 20.8/38.7 MB 27.3 MB/s eta 0:00:01
   ---------------------- ----------------- 21.6/38.7 MB 25.2 MB/s eta 0:00:01
   ----------------------- ---------------- 23.0/38.7 MB 27.3 MB/s eta 0:00:01
   ------------------------- -------------- 24.4/38.7 MB 27.3 MB/s eta 0:00:01
   -------------------------- ------------- 25.5/38.7 MB 28.4 MB/s eta 0:00:01
   --------------------------- ------------ 26.9/38.7 MB 28.4 MB/s eta 0:00:01
   ---------------------------- ----------- 28.0/38.7 MB 28.5 MB/s eta 0:00:01
   ----------------------------- ---------- 29.0/38.7 MB 29.7 MB/s eta 0:00:01
   ------------------------------- -------- 30.2/38.7 MB 28.5 MB/s eta 0:00:01
   -------------------------------- ------- 31.7/38.7 MB 31.2 MB/s eta 0:00:01
   ---------------------------------- ----- 33.4/38.7 MB 31.2 MB/s eta 0:00:01
   ----------------------------------- ---- 34.2/38.7 MB 29.7 MB/s eta 0:00:01
   ------------------------------------ --- 35.1/38.7 MB 29.8 MB/s eta 0:00:01
   ------------------------------------- -- 36.4/38.7 MB 29.7 MB/s eta 0:00:01
   -------------------------------------- - 37.7/38.7 MB 28.5 MB/s eta 0:00:01
   ---------------------------------------  38.7/38.7 MB 32.7 MB/s eta 0:00:01
   ---------------------------------------  38.7/38.7 MB 32.7 MB/s eta 0:00:01
   ---------------------------------------- 38.7/38.7 MB 27.3 MB/s eta 0:00:00
Downloading statsmodels-0.14.6-cp311-cp311-win_amd64.whl (9.6 MB)
   ---------------------------------------- 0.0/9.6 MB ? eta -:--:--
   -- ------------------------------------- 0.7/9.6 MB 41.0 MB/s eta 0:00:01
   -------- ------------------------------- 2.2/9.6 MB 34.0 MB/s eta 0:00:01
   -------------- ------------------------- 3.6/9.6 MB 32.3 MB/s eta 0:00:01
   --------------------- ------------------ 5.1/9.6 MB 36.1 MB/s eta 0:00:01
   --------------------------- ------------ 6.7/9.6 MB 35.5 MB/s eta 0:00:01
   ------------------------------- -------- 7.7/9.6 MB 34.9 MB/s eta 0:00:01
   -------------------------------------- - 9.1/9.6 MB 36.5 MB/s eta 0:00:01
   ---------------------------------------- 9.6/9.6 MB 32.2 MB/s eta 0:00:00
Downloading tqdm-4.67.3-py3-none-any.whl (78 kB)
   ---------------------------------------- 0.0/78.4 kB ? eta -:--:--
   ---------------------------------------- 78.4/78.4 kB 4.3 MB/s eta 0:00:00
Downloading typeguard-4.5.1-py3-none-any.whl (36 kB)
Downloading visions-0.8.1-py3-none-any.whl (105 kB)
   ---------------------------------------- 0.0/105.4 kB ? eta -:--:--
   ---------------------------------------- 105.4/105.4 kB ? eta 0:00:00
Downloading wordcloud-1.9.6-cp311-cp311-win_amd64.whl (306 kB)
   ---------------------------------------- 0.0/306.1 kB ? eta -:--:--
   --------------------------------------- 306.1/306.1 kB 18.5 MB/s eta 0:00:00
Downloading annotated_types-0.7.0-py3-none-any.whl (13 kB)
Downloading attrs-25.4.0-py3-none-any.whl (67 kB)
   ---------------------------------------- 0.0/67.6 kB ? eta -:--:--
   ---------------------------------------- 67.6/67.6 kB 3.6 MB/s eta 0:00:00
Downloading llvmlite-0.45.1-cp311-cp311-win_amd64.whl (38.1 MB)
   ---------------------------------------- 0.0/38.1 MB ? eta -:--:--
   - -------------------------------------- 1.4/38.1 MB 43.3 MB/s eta 0:00:01
   -- ------------------------------------- 2.8/38.1 MB 36.1 MB/s eta 0:00:01
   ---- ----------------------------------- 4.2/38.1 MB 38.0 MB/s eta 0:00:01
   ----- ---------------------------------- 5.4/38.1 MB 34.3 MB/s eta 0:00:01
   ------ --------------------------------- 5.8/38.1 MB 28.7 MB/s eta 0:00:02
   ------- -------------------------------- 7.0/38.1 MB 29.8 MB/s eta 0:00:02
   -------- ------------------------------- 8.3/38.1 MB 29.4 MB/s eta 0:00:02
   --------- ------------------------------ 9.4/38.1 MB 30.1 MB/s eta 0:00:01
   ----------- ---------------------------- 11.0/38.1 MB 29.7 MB/s eta 0:00:01
   ------------- -------------------------- 12.6/38.1 MB 31.2 MB/s eta 0:00:01
   ------------- -------------------------- 13.3/38.1 MB 28.4 MB/s eta 0:00:01
   --------------- ------------------------ 14.9/38.1 MB 28.4 MB/s eta 0:00:01
   ---------------- ----------------------- 16.1/38.1 MB 32.7 MB/s eta 0:00:01
   ------------------ --------------------- 17.3/38.1 MB 32.7 MB/s eta 0:00:01
   ------------------- -------------------- 18.9/38.1 MB 34.4 MB/s eta 0:00:01
   --------------------- ------------------ 20.4/38.1 MB 32.7 MB/s eta 0:00:01
   ---------------------- ----------------- 21.1/38.1 MB 32.8 MB/s eta 0:00:01
   ----------------------- ---------------- 22.6/38.1 MB 32.8 MB/s eta 0:00:01
   ------------------------- -------------- 24.1/38.1 MB 34.4 MB/s eta 0:00:01
   -------------------------- ------------- 25.7/38.1 MB 34.4 MB/s eta 0:00:01
   ---------------------------- ----------- 27.0/38.1 MB 34.4 MB/s eta 0:00:01
   ----------------------------- ---------- 27.9/38.1 MB 34.4 MB/s eta 0:00:01
   ------------------------------ --------- 29.2/38.1 MB 32.8 MB/s eta 0:00:01
   -------------------------------- ------- 31.1/38.1 MB 34.4 MB/s eta 0:00:01
   ---------------------------------- ----- 32.8/38.1 MB 34.4 MB/s eta 0:00:01
   ------------------------------------ --- 34.3/38.1 MB 36.4 MB/s eta 0:00:01
   ------------------------------------ --- 34.7/38.1 MB 34.4 MB/s eta 0:00:01
   ------------------------------------ --- 34.7/38.1 MB 29.7 MB/s eta 0:00:01
   ------------------------------------ --- 34.8/38.1 MB 29.7 MB/s eta 0:00:01
   ------------------------------------ --- 34.9/38.1 MB 24.2 MB/s eta 0:00:01
   ------------------------------------ --- 35.0/38.1 MB 22.5 MB/s eta 0:00:01
   ------------------------------------- -- 35.4/38.1 MB 20.5 MB/s eta 0:00:01
   ------------------------------------- -- 35.7/38.1 MB 19.2 MB/s eta 0:00:01
   ---------------------------------------  37.3/38.1 MB 19.2 MB/s eta 0:00:01
   ---------------------------------------  38.0/38.1 MB 18.7 MB/s eta 0:00:01
   ---------------------------------------  38.1/38.1 MB 18.7 MB/s eta 0:00:01
   ---------------------------------------- 38.1/38.1 MB 16.8 MB/s eta 0:00:00
Downloading networkx-3.6.1-py3-none-any.whl (2.1 MB)
   ---------------------------------------- 0.0/2.1 MB ? eta -:--:--
   -------------------------------- ------- 1.7/2.1 MB 53.5 MB/s eta 0:00:01
   ---------------------------------------- 2.1/2.1 MB 32.7 MB/s eta 0:00:00
Downloading patsy-1.0.2-py2.py3-none-any.whl (233 kB)
   ---------------------------------------- 0.0/233.3 kB ? eta -:--:--
   ---------------------------------------- 233.3/233.3 kB ? eta 0:00:00
Downloading typing_extensions-4.15.0-py3-none-any.whl (44 kB)
   ---------------------------------------- 0.0/44.6 kB ? eta -:--:--
   ---------------------------------------- 44.6/44.6 kB 2.1 MB/s eta 0:00:00
Downloading typing_inspection-0.4.2-py3-none-any.whl (14 kB)
Downloading puremagic-1.30-py3-none-any.whl (43 kB)
   ---------------------------------------- 0.0/43.3 kB ? eta -:--:--
   ---------------------------------------- 43.3/43.3 kB ? eta 0:00:00
Downloading pywavelets-1.9.0-cp311-cp311-win_amd64.whl (4.2 MB)
   ---------------------------------------- 0.0/4.2 MB ? eta -:--:--
   -------------- ------------------------- 1.5/4.2 MB 47.4 MB/s eta 0:00:01
   -------------------------------- ------- 3.4/4.2 MB 42.8 MB/s eta 0:00:01
   ---------------------------------------- 4.2/4.2 MB 38.3 MB/s eta 0:00:00
Installing collected packages: puremagic, minify-html, filetype, typing-extensions, tqdm, scipy, requests, PyYAML, PyWavelets, patsy, networkx, multimethod, llvmlite, dacite, attrs, annotated-types, typing-inspection, typeguard, pydantic-core, numba, imagehash, wordcloud, visions, statsmodels, pydantic, phik, ydata-profiling
  Attempting uninstall: scipy
    Found existing installation: scipy 1.17.0
    Uninstalling scipy-1.17.0:

[notice] A new release of pip is available: 24.0 -> 26.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [6]:
!python -m pip install ipywidgets

Collecting ipywidgets

[notice] A new release of pip available: 22.3 -> 26.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip

  Downloading ipywidgets-8.1.8-py3-none-any.whl (139 kB)
     -------------------------------------- 139.8/139.8 kB 8.1 MB/s eta 0:00:00
Collecting jupyterlab_widgets~=3.0.15
  Downloading jupyterlab_widgets-3.0.16-py3-none-any.whl (914 kB)
     -------------------------------------- 914.9/914.9 kB 7.2 MB/s eta 0:00:00
Requirement already satisfied: traitlets>=4.3.1 in c:\users\hnico\appdata\roaming\python\python310\site-packages (from ipywidgets) (5.14.3)
Requirement already satisfied: ipython>=6.1.0 in c:\users\hnico\appdata\roaming\python\python310\site-packages (from ipywidgets) (8.38.0)
Requirement already satisfied: comm>=0.1.3 in c:\users\hnico\appdata\roaming\python\python310\site-packages (from ipywidgets) (0.2.3)
Collecting widgetsnbextension~=4.0.14
  Downloading widgetsnbextension-4.0.15-py3-none-any.whl (2.2 MB)
     ---------------------------------------- 2.2/2.2 MB 10.0 MB/s eta 0:00:00
Requirement already satisfied: stack_data in c:\users\hnico\appdata\roaming\python\python310\site-packages (from ipython>=6.1.0->ipywidgets) (0.6.3)
Requirement already satisfied: matplotlib-inline in c:\users\hnico\appdata\roaming\python\python310\site-packages (from ipython>=6.1.0->ipywidgets) (0.2.1)
Requirement already satisfied: decorator in c:\users\hnico\appdata\roaming\python\python310\site-packages (from ipython>=6.1.0->ipywidgets) (5.2.1)
Requirement already satisfied: pygments>=2.4.0 in c:\users\hnico\appdata\roaming\python\python310\site-packages (from ipython>=6.1.0->ipywidgets) (2.19.2)
Requirement already satisfied: prompt_toolkit<3.1.0,>=3.0.41 in c:\users\hnico\appdata\roaming\python\python310\site-packages (from ipython>=6.1.0->ipywidgets) (3.0.52)
Requirement already satisfied: exceptiongroup in c:\users\hnico\appdata\roaming\python\python310\site-packages (from ipython>=6.1.0->ipywidgets) (1.3.1)
Requirement already satisfied: jedi>=0.16 in c:\users\hnico\appdata\roaming\python\python310\site-packages (from ipython>=6.1.0->ipywidgets) (0.19.2)
Requirement already satisfied: typing_extensions>=4.6 in c:\users\hnico\appdata\roaming\python\python310\site-packages (from ipython>=6.1.0->ipywidgets) (4.15.0)
Requirement already satisfied: colorama in c:\users\hnico\appdata\local\programs\python\python310\lib\site-packages (from ipython>=6.1.0->ipywidgets) (0.4.5)
Requirement already satisfied: parso<0.9.0,>=0.8.4 in c:\users\hnico\appdata\roaming\python\python310\site-packages (from jedi>=0.16->ipython>=6.1.0->ipywidgets) (0.8.6)
Requirement already satisfied: wcwidth in c:\users\hnico\appdata\roaming\python\python310\site-packages (from prompt_toolkit<3.1.0,>=3.0.41->ipython>=6.1.0->ipywidgets) (0.6.0)
Requirement already satisfied: executing>=1.2.0 in c:\users\hnico\appdata\roaming\python\python310\site-packages (from stack_data->ipython>=6.1.0->ipywidgets) (2.2.1)
Requirement already satisfied: asttokens>=2.1.0 in c:\users\hnico\appdata\roaming\python\python310\site-packages (from stack_data->ipython>=6.1.0->ipywidgets) (3.0.1)
Requirement already satisfied: pure-eval in c:\users\hnico\appdata\roaming\python\python310\site-packages (from stack_data->ipython>=6.1.0->ipywidgets) (0.2.3)
Installing collected packages: widgetsnbextension, jupyterlab_widgets, ipywidgets
Successfully installed ipywidgets-8.1.8 jupyterlab_widgets-3.0.16 widgetsnbextension-4.0.15

In [1]:
import numpy as np
import pandas as pd
import datetime
from datetime import datetime, timedelta

# import matplotlib
from matplotlib import pyplot
import matplotlib.pyplot as plt
from matplotlib.pyplot import figure
import matplotlib.image as mpimg

# import seaborn
import seaborn as sns

pd.set_option('display.max_columns', None)
pd.set_option("display.max_rows", 50)
import warnings
warnings.filterwarnings('ignore')

In [2]:
# to be able to see multiple outputs from single cell
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = "all"

#### Import data

In [3]:
processed_df = pd.read_csv('../../data/processed/final_for_EDA/ttc_cleaned_final_with_peaktimes.csv')
code_description_df = pd.read_csv('../../data/raw/CodeDescriptions.csv')

In [4]:
processed_df.info()
processed_df

code_description_df.info()
code_description_df

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20316 entries, 0 to 20315
Data columns (total 15 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   year           20316 non-null  int64
 1   month          20316 non-null  object
 2   date           20316 non-null  object
 3   time           20316 non-null  object
 4   day            20316 non-null  object
 5   station        20316 non-null  object
 6   code           20316 non-null  object
 7   min_delay      20316 non-null  int64
 8   min_gap        20316 non-null  int64
 9   bound          20316 non-null  object
 10  line           20316 non-null  object
 11  vehicle        20316 non-null  int64
 12  time_hms       20316 non-null  object
 13  time_category  20316 non-null  object
 14  day_category   20316 non-null  object
dtypes: int64(4), object(11)
memory usage: 2.3+ MB

,year,month,date,time,day,station,code,min_delay,min_gap,bound,line,vehicle,time_hms,time_category,day_category
0,2025,March,2025-03-16,13:49,Sunday,old mill,PUTIJ,10,14,E,BD,5103,13:49:00,Mid_Day,Weekend
1,2025,January,2025-01-01,2:10,Wednesday,bathurst,MUSAN,5,9,E,BD,5227,02:10:00,Early_AM,Holiday
2,2025,February,2025-02-05,20:38,Wednesday,bathurst,SUDP,5,9,W,BD,5148,20:38:00,Evening,Weekday
3,2025,March,2025-03-21,11:40,Friday,bathurst,MUDD,5,9,W,BD,5170,11:40:00,Mid_Day,Weekday
4,2025,June,2025-06-11,15:32,Wednesday,bathurst,SUO,5,9,E,BD,5035,15:32:00,PM_Peak,Weekday
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
20311,2021,July,2021-07-02,22:20,Friday,yorkdale,SUDP,5,12,N,YU,5691,22:20:00,Late_Evening,Weekday
20312,2021,July,2021-07-27,18:04,Tuesday,yorkdale,TUO,5,8,S,YU,5431,18:04:00,PM_Peak,Weekday
20313,2021,August,2021-08-08,18:23,Sunday,yorkdale,MUO,5,10,S,YU,5856,18:23:00,PM_Peak,Weekend
20314,2026,January,2026-01-25,17:23,Sunday,yorkdale,PUTIS,5,10,N,YU,6056,17:23:00,PM_Peak,Weekend
20315,2025,July,2025-07-11,9:40,Friday,yorkdale,PUTO,65,69,N,YU,5651,09:40:00,Mid_Day,Weekday

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 140 entries, 0 to 139
Data columns (total 3 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   _id          140 non-null    int64
 1   CODE         140 non-null    object
 2   DESCRIPTION  140 non-null    object
dtypes: int64(1), object(2)
memory usage: 3.4+ KB

     _id   CODE                              DESCRIPTION
0      1   EUAC                         AIR CONDITIONING
1      2   EUAL                      ALTERNATING CURRENT
2      3  EUATC                       ATC RC&S EQUIPMENT
3      4   EUBK                                   BRAKES
4      5   EUBO                                     BODY
..   ...    ...                                      ...
135  136   TUSC                       OPERATOR OVERSPEED
136  137  TUSET           CONTROLS IMPROPERLY BLOWN DOWN
137  138   TUST                             STORM TRAINS
138  139  TUSUP                        SUPERVISORY ERROR
139  140   TUUR  UNAUTHORIZED TRAIN REVERSAL BY OPERATOR

[140 rows x 3 columns]

### EDA Using YData Profiling

In [7]:
from ydata_profiling import ProfileReport

profile = ProfileReport(processed_df)
profile.to_notebook_iframe()

100%|██████████| 15/15 [00:03<00:00,  4.79it/s]4<00:03,  1.62it/s, Describe variable: day_category]
Summarize dataset: 100%|██████████| 40/40 [00:06<00:00,  6.22it/s, Completed]
Generate report structure: 100%|██████████| 1/1 [00:03<00:00,  3.81s/it]
Render HTML: 100%|██████████| 1/1 [00:00<00:00,  2.93it/s]

In [2]:
import streamlit as st
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

st.title("TTC Delay Analytics Dashboard")

df = pd.read_csv("../../data/processed/ttc_feature_engineered_final.csv")

# Sidebar filters
line_filter = st.sidebar.multiselect("Line", df["line"].unique())
station_filter = st.sidebar.multiselect("Station", df["station"].unique())

filtered_df = df.copy()

if line_filter:
    filtered_df = filtered_df[filtered_df["line"].isin(line_filter)]

if station_filter:
    filtered_df = filtered_df[filtered_df["station"].isin(station_filter)]

# KPIs
col1, col2, col3 = st.columns(3)

col1.metric("Total Delays", len(filtered_df))
col2.metric("Average Delay", round(filtered_df["min_delay"].mean(),1))
col3.metric("High Delay %",
            round((filtered_df["min_delay"]>=20).mean()*100,1))

# Top delay causes
st.subheader("Top Delay Causes")

cause_counts = filtered_df["code_reduced"].value_counts().head(10)

fig, ax = plt.subplots()
sns.barplot(x=cause_counts.values, y=cause_counts.index, ax=ax)

st.pyplot(fig)

# Delay by hour
st.subheader("Delays by Hour")

hour_counts = filtered_df.groupby("hour").size()

fig, ax = plt.subplots()
hour_counts.plot(ax=ax)

st.pyplot(fig)

2026-03-06 19:56:00.258 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-03-06 19:56:00.265 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-03-06 19:56:00.273 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-03-06 19:56:00.537 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-03-06 19:56:00.540 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-03-06 19:56:00.565 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-03-06 19:56:00.574 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-03-06 19:56:00.575 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-03-06 19:56:00.576 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-03-06 19:56:00.578 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-03-06 19:56:00.579 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-03-06 19:56:00.580 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-03-06 19:56:00.582 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-03-06 19:56:00.584 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-03-06 19:56:00.585 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-03-06 19:56:00.593 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-03-06 19:56:00.594 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-03-06 19:56:00.595 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-03-06 19:56:00.596 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-03-06 19:56:00.600 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-03-06 19:56:00.601 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-03-06 19:56:00.602 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-03-06 19:56:00.617 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-03-06 19:56:00.618 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-03-06 19:56:00.619 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-03-06 19:56:00.630 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-03-06 19:56:00.631 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-03-06 19:56:00.632 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-03-06 19:56:00.633 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-03-06 19:56:00.634 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-03-06 19:56:00.635 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-03-06 19:56:01.539 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-03-06 19:56:01.830 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-03-06 19:56:01.831 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-03-06 19:56:01.832 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-03-06 19:56:01.834 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-03-06 19:56:01.835 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-03-06 19:56:01.836 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-03-06 19:56:02.040 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-03-06 19:56:02.149 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-03-06 19:56:02.150 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-03-06 19:56:02.152 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.

DeltaGenerator()

In [3]:
df

,Unnamed: 0,year,month,date,time,day,station,code,min_delay,min_gap,...,time_category,day_category,code_reduced,hour,month_num,hour_sin,hour_cos,station_freq,station_code_likelihood,delay_category
0,0,2025,March,2025-03-16,13:49,Sunday,old mill,PUTIJ,10,14,...,Mid_Day,Weekend,PU,13,3,-0.258819,-9.659258e-01,127,0.015748,Low
1,1,2025,January,2025-01-01,2:10,Wednesday,bathurst,MUSAN,5,9,...,Early_AM,Holiday,MU,2,1,0.500000,8.660254e-01,161,0.037267,Low
2,2,2025,February,2025-02-05,20:38,Wednesday,bathurst,SUDP,5,9,...,Evening,Weekday,SU,20,2,-0.866025,5.000000e-01,161,0.211180,Low
3,3,2025,March,2025-03-21,11:40,Friday,bathurst,MUDD,5,9,...,Mid_Day,Weekday,MU,11,3,0.258819,-9.659258e-01,161,0.080745,Low
4,4,2025,June,2025-06-11,15:32,Wednesday,bathurst,SUO,5,9,...,PM_Peak,Weekday,SU,15,6,-0.707107,-7.071068e-01,161,0.105590,Low
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
20311,20311,2021,July,2021-07-02,22:20,Friday,yorkdale,SUDP,5,12,...,Late_Evening,Weekday,SU,22,7,-0.500000,8.660254e-01,279,0.096774,Low
20312,20312,2021,July,2021-07-27,18:04,Tuesday,yorkdale,TUO,5,8,...,PM_Peak,Weekday,TU,18,7,-1.000000,-1.836970e-16,279,0.017921,Low
20313,20313,2021,August,2021-08-08,18:23,Sunday,yorkdale,MUO,5,10,...,PM_Peak,Weekend,MU,18,8,-1.000000,-1.836970e-16,279,0.025090,Low
20314,20314,2026,January,2026-01-25,17:23,Sunday,yorkdale,PUTIS,5,10,...,PM_Peak,Weekend,PU,17,1,-0.965926,-2.588190e-01,279,0.007168,Low
20315,20315,2025,July,2025-07-11,9:40,Friday,yorkdale,PUTO,65,69,...,Mid_Day,Weekday,PU,9,7,0.707107,-7.071068e-01,279,0.010753,Extreme